<?php
session_start();
##### ERROR 0
//error_reporting(E_ALL);
$idPage  = $_GET['id'];


if( !$_SESSION['id_admon'] )
		{

?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
<base href="<?php echo URL_BASE ?>" target="_top" />
<title>Admin</title>
<meta name="robots" content="noindex,nofollow">
<link rel="stylesheet" type="text/css" href="<?php echo URL_BASE; ?>public/admin/css/layout.css"/>
<script type="text/javascript" src="<?php echo $_layoutParams['root_js']; ?>modernizr.custom.js"></script>		
		<link rel="shortcut icon" href="<?php echo $_layoutParams['root_img']; ?>favicon.ico" />

</head>

	<body id="pattern">
			
			<div class="form_login">
<form action="" method="post" id="access">
                      <label for="usr"><img src="<?php echo URL_BASE; ?>public/admin/img/user.png" /> User:</label><br />
                      <input type="text" value="" size="15" name="usr" id="usr" /><br />
                      <!--CONTRASEÑA -->
                      <label for="password"><img src="<?php echo URL_BASE; ?>public/admin/img/pass.png" /> Password:</label><br />
                      <input type="password" id="pass" value="" size="15" name="pass" /><br />
                      <div class="clear"></div>
                      <input type="submit" name="submit" value="Log in" id="buttonLogin" class="bt_login" />
     </form>
     </div>
		

<script src="<?php echo $_layoutParams['root_js']; ?>jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="<?php echo URL_BASE; ?>public/admin/js/login.js"></script>

 </body>
</html>
<?php
		} 
else {

				include( '_views/controller.php' ); 
}
		?>
