<?php 
$countPost = count($this->posts);
if( $this->infoSession->status == 'active' ):
include 'views/inc/header.php'; ?>
<style>
	
	body
	{
		background-position: <?php echo $this->infoSession->bg_position; ?> 65px;
		background-attachment: <?php echo $this->infoSession->bg_attachment; ?>;
		
		<?php if( $this->infoSession->bg_attachment == 'fixed' ): ?>
		background-repeat: repeat repeat; 
		<?php else: ?>
		background-repeat: no-repeat; 
		<?php endif; ?>
		
		background-color: <?php echo $this->infoSession->bg_color; ?>;
		
		<?php if( $this->infoSession->bg != '' ): ?>
		background-image: url(<?php echo URL_BASE.'public/backgrounds/'.$this->infoSession->bg; ?>);
		<?php endif; ?>
	}
	
	body a,
	body a:hover { color: <?php echo $this->infoSession->color_link; ?>; }
	
	.icons { background-color: <?php echo $this->infoSession->color_link; ?>;}
	
</style>
<link href="<?php echo $_layoutParams['root_css']; ?>colorbox.css" rel="stylesheet" />
</head>
<!-- Body -->
	<body data-max="<?php echo MAX_LENGTH; ?>">
		
		<!-- warpper_top_bar -->
		<div class="warpper_top_bar">
				<!-- inner_top_bar -->
				<header class="inner_top_bar">
					<!-- padding_class -->
					<div class="padding_class">
						<?php include 'views/inc/logo.php'; ?>
					    <?php include 'views/inc/navigation.php'; ?>
			    </div><!-- padding_class -->
			</header><!-- inner_top_bar -->
		</div><!-- warpper_top_bar -->
	
	<!-- page -->
	<div class="page">
		<!-- layout -->
		<section class="layout session">
			<div class="popout"></div>
			<!-- padding_class -->
		    <div class="padding_class sessionClass">
		    	<div class="formSearchResp">
						   <form action="search/" class="formResponsive" method="get" id="search_engine" accept-charset="UTF-8">
							  <input id="btnItems" name="q" class="mention" type="text" placeholder="Search..." maxlength="100">	
						      </form>
					</div>
		    <!-- wrapper_grid -->
		     <div class="wrapper_grid floatLeft">
				   
				   <?php 
				   //<---- * profile_static * --->
				   include 'views/inc/profile_static.php'; 
				   //<---- * advertising * --->
				   include 'views/inc/advertising.php';
				   //<---- * who_follow * --->
				   include 'views/inc/who_to_follow.php';
				   //<---- * trending * --->
				   include 'views/inc/trending.php'; 
				    ?>
				   
				    <!-- Grid 1 -->
				   <div class="grid_1">
				   		<!-- container_grid -->
				   		<div class="container_grid about_pages">
				   			<?php include 'views/inc/footer_session.php'; ?>
				   		</div><!-- container_grid -->
				   </div><!-- Grid 1 -->
				   
				   
			   </div><!-- wrapper_grid -->
			   
			   <!-- Grid 2 -->
			   <div class="grid_2 floatRight">
			   <?php include 'views/inc/posts.php'; ?>
			    </div><!-- Grid 2 -->
			   		
			 </div><!-- padding_class -->
		</section><!-- layout -->
	</div><!-- page -->
	<div class="modal">
		<div id="content_modal">
		</div>
	</div>
	
	
   
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery-1.7.1.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.easing.1.3.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.placeholder.1.1.1.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery-ui-1.8.17.custom.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>functions.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>count.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>add.post.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.form.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jqueryTimeago.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.colorbox.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.scroll.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>ajax.timeline.js"></script>
  
   <script type="text/javascript">
   
   $(".galeryAjax").colorbox({
   	fixed: false,
   	maxHeight: 550
   	});
   	
   jQuery(document).ready(function($) {

   <?php if( $countPost != 0 ): ?>

   $('.posts').scrollPagination({
		nop     : 10,
		offset  : 0,
		error   : '',
		delay   : 250,
		              
		scroll  : true, 
		query   : 0,
		file    : 'get_all_post.php',
		totalGlobal :  <?php echo $countPost; ?>
	});
	
	<?php endif; ?>
	
   //====== TIME AGO
	
   //=== COUNTER
   $('#add_post').live('hover', function(){
		if ($(this).data('hascharcount') == undefined) {
			$(this).data('hascharcount', true).charCount({ allowed: <?php echo MAX_LENGTH; ?>, warning: 10 });
		}
		});
		
		$('#reply_post').live('hover', function(){
		if ($(this).data('hascharcount') == undefined) {
			$(this).data('hascharcount', true).charCount({ allowed: <?php echo MAX_LENGTH; ?>, warning: 10 });
		}
		});
  
  //=== PLACEHOLDER	
  $(function(){
      $(':input[placeholder]').placeholder();
    });
    
    
    //=================== * UPLOAD  * ===============//
    $('#upload').live('change', function(){     		 
	  $('<div id="loader_gif"></div>').insertBefore('#upload');
	  $('#button_add').attr({'disabled' : 'true'}).css({'opacity':'0.5','cursor':'default'});
					
			
			(function() {
	  		
	  		$("#form_add_post").ajaxForm({
	  		
	  		dataType : 'json',	
			success:  function(e)
			{
				if( e )
				{
					if( e.error == 1 )
					{
						$('#loader_gif').remove();
					}
					
					$('#wrapper_preview').show();
					$('#container_preview').html( ''+ e.output +'' ).show();
					$('#upload').val('');
					
					if( e.error == 0 )
					{
						$('#loader_gif').css({background:'url("<?php echo URL_BASE; ?>thumb_fixed/30-30-upload/'+ e.photo +'") center center no-repeat #FFF'}).addClass('deletePhoto').attr( 'data',e.photo ).attr( 'title','Delete Image' );
						$('#wrapper_preview').show();
						$('#photoId').val(e.photo);
						$('#button_add').removeAttr('disabled').css({'opacity':'1','cursor':'pointer'});
					}
					
				}
				else 
				{
					jAlert('Upload Error');
					$('#upload').val('');
					$('#button_add').removeAttr('disabled').css({'opacity':'1','cursor':'pointer'});
					
				}
			}//<----- SUCCESS
			
		}).submit();
		})(); //<--- FUNCTION %
	});//<--- LIVE
	
		//===== DELETE PHOTO
		$(".deletePhoto").live('click',function(){ 
					//=== PARAM
					var element     = $(this);
					var id          = element.attr("data");
					var info        = 'token_id=' + id;
					var add_post_   = $('#add_post').val();
					var video_link_ = $('#video_link').val();
								   		
					$.ajax({
					   type: "GET",
					   url: "<?php echo URL_BASE; ?>public/ajax/delete_id_photo.php",
					   data: info,
					   success: function(output){
					   if( output == 'TRUE' )
					   {
					   	if( add_post_ == 0 && video_link_ == 0 )
					   	{
					   		$('#button_add').attr({'disabled' : 'true'}).css({'opacity':'0.5','cursor':'default'});
					   	}
					   	
					   	$('#photoId').val('');
					   	element.fadeOut('fast',function(){
				   		  element.remove();
				   		});//<-- FUNCTION
					   }
					   
					 }
									
				});//<-- AJAX
			});//<--- CLICK
    
});//<-------- * DOM * ------>

  </script>
	</body>
</html>
  <?php
else:
	
	session_destroy();
    
	endif; ?>
   
