<?php 
$countPost = count($this->data);
include 'views/inc/header.php'; ?>
<?php if( Session::get( 'authenticated' ) ) : ?>
<style>
	
	body
	{
		background-position: <?php echo $this->infoSession->bg_position; ?> 65px;
		background-attachment: <?php echo $this->infoSession->bg_attachment; ?>;
		
		<?php if( $this->infoSession->bg_attachment == 'fixed' ): ?>
		background-repeat: repeat repeat; 
		<?php else: ?>
		background-repeat: no-repeat; 
		<?php endif; ?>
		
		background-color: <?php echo $this->infoSession->bg_color; ?>;
		
		<?php if( $this->infoSession->bg != '' ): ?>
		background-image: url(<?php echo URL_BASE.'public/backgrounds/'.$this->infoSession->bg; ?>);
		<?php endif; ?>
	}
	
	body a,
	body a:hover { color: <?php echo $this->infoSession->color_link; ?>; }
	
	.icons { background-color: <?php echo $this->infoSession->color_link; ?>;}
</style>
<?php endif;//<<<---------- * Session Active * -------->>>> ?>

<link href="<?php echo $_layoutParams['root_css']; ?>colorbox.css" rel="stylesheet" />
</head>
<!-- Body -->
	<body data-max="<?php echo MAX_LENGTH; ?>">
		
		<!-- warpper_top_bar -->
		<div class="warpper_top_bar">
				<!-- inner_top_bar -->
				<header class="inner_top_bar">
					<!-- padding_class -->
					<div class="padding_class">
						<a href="<?php echo URL_BASE; ?>">
						<?php include 'views/inc/logo.php'; ?>
						</a>
					    <?php include 'views/inc/navigation.php'; ?>
			    </div><!-- padding_class -->
			</header><!-- inner_top_bar -->
		</div><!-- warpper_top_bar -->
	
	<!-- page -->
	<div class="page">
		<!-- layout -->
		<section class="layout session">
			<div class="popout"></div>
			<!-- padding_class -->
		    <div class="padding_class sessionClass">
		    	
		    	<div class="formSearchResp">
						   <form action="search/" class="formResponsive" method="get" id="search_engine" accept-charset="UTF-8">
							  <input id="btnItems" name="q" class="mention" type="text" placeholder="Search..." maxlength="100">	
						      </form>
					</div>
		    <!-- wrapper_grid -->
		     <div class="wrapper_grid floatLeft">
				   
				    <!-- Grid 1 -->
				   <div class="grid_1">
				   		<!-- container_grid -->
				   		<div class="container_grid">
				   		    <ul class="settingsList">
				   		    	<li>
				   		    		<a href="<?php echo URL_BASE; ?>search/?q=<?php echo str_replace( '#', '%23', $_GET['q'] ) ?>">Posts</a>
				   		    	</li>
				   		    	<li class="lastSet">
				   		    		<a href="<?php echo URL_BASE; ?>search/?user=true&q=<?php echo str_replace( '#', '%23', $_GET['q'] ) ?>">People</a>
				   		    	</li>
				   		    </ul>
				   		   		</div><!-- container_grid -->
				   </div><!-- Grid 1 -->
				   
				   <?php 
				   //<---- * advertising * --->
				   include 'views/inc/advertising.php';
				   ?>
				   
				   <?php
				   if( Session::get( 'authenticated' ) ) :
				   //<---- * who_follow * --->
				   include 'views/inc/who_to_follow.php';
				   
				   endif;
				   //<---- * trending * --->
				   include 'views/inc/trending.php'; 
				    ?>
				   
				    <!-- Grid 1 -->
				   <div class="grid_1">
				   		<!-- container_grid -->
				   		<div class="container_grid about_pages">
				   			<?php include 'views/inc/footer_session.php'; ?>
				   		</div><!-- container_grid -->
				   </div><!-- Grid 1 -->
				   
				   
			   </div><!-- wrapper_grid -->
			   
			   <!-- Grid 2 -->
			   <div class="grid_2 floatRight">
			   <?php include 'views/inc/search_listing.php'; ?>
			    </div><!-- Grid 2 -->
			   		
			 </div><!-- padding_class -->
		</section><!-- layout -->
	</div><!-- page -->
	
	
   
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery-1.7.1.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.easing.1.3.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.placeholder.1.1.1.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery-ui-1.8.17.custom.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>functions.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>count.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.form.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jqueryTimeago.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.colorbox.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.scroll.user.js"></script>
   
   
   <?php if( !isset( $_GET['user'] ) ):?>
   <script src="<?php echo $_layoutParams['root_js']; ?>search.timeline.js"></script>
   <?php endif; ?>
   
   <?php if( !Session::get( 'authenticated' ) ) : ?>
   <script src="<?php echo $_layoutParams['root_js']; ?>login.sign.up.js"></script>
   <?php endif; ?>
   
   <script type="text/javascript">
   
   $(".galeryAjax").colorbox({
   	fixed: false,
   	maxHeight: 550
   	});
   	
   	$('.posts').scrollPagination({
		nop     : 10,
		offset  : 0,
		error   : '',
		delay   : 250,
		              
		scroll  : true, 
		query   : 0,
		file    : '<?php echo $this->_file; ?>',
		_userId : '<?php echo addslashes( $_GET['q'] ); ?>',
		totalGlobal :  <?php echo $countPost; ?>
	});

   jQuery(document).ready(function($) {

	 $('#reply_post').live('hover', function(){
		if ($(this).data('hascharcount') == undefined) {
			$(this).data('hascharcount', true).charCount({ allowed: <?php echo MAX_LENGTH; ?>, warning: 10 });
		}
		});
    
});//<-------- * DOM * ------>

  </script>
	</body>
</html>
