<?php 
//<--- * User * ---> 
$count = count( $this->data );

//<--- * Last Photos * --->
$countMedia = count( $this->_media );

if( isset( $this->data ) &&  $count != 0 && $this->checkBlocked[0]['status'] != 1 ) :

?>
<?php include 'views/inc/header.php'; ?>
<link rel="canonical" href="<?php echo URL_BASE.$this->info->username.'/media' ?>">
<style>
	
	body
	{
		background-position: <?php echo $this->info->bg_position; ?> 65px;
		background-attachment: <?php echo $this->info->bg_attachment; ?>;
		
		<?php if( $this->info->bg_attachment == 'fixed' ): ?>
		background-repeat: repeat repeat; 
		<?php else: ?>
		background-repeat: no-repeat; 
		<?php endif; ?>
		
		background-color: <?php echo $this->info->bg_color; ?>;
		
		<?php if( $this->info->bg != '' ): ?>
		background-image: url(<?php echo URL_BASE.'public/backgrounds/'.$this->info->bg; ?>);
		<?php endif; ?>
	}
	
	body a,
	body a:hover { color: <?php echo $this->info->color_link; ?>; }
	.icons { background-color: <?php echo $this->info->color_link; ?>;}
	.container_data_profile a:hover span{ color: <?php echo $this->info->color_link; ?>;  }
	
</style>
<link href="<?php echo $_layoutParams['root_css']; ?>colorbox.css" rel="stylesheet" />
</head>
	<!-- Body -->
	<body data-max="<?php echo MAX_LENGTH; ?>">
		<!-- warpper_top_bar -->
		<div class="warpper_top_bar">
				<!-- inner_top_bar -->
				<header class="inner_top_bar">
					<!-- padding_class -->
					<div class="padding_class">
						<a href="<?php echo URL_BASE; ?>">
							<?php include 'views/inc/logo.php'; ?>
						</a>
					
					<?php include 'views/inc/navigation.php'; ?>
			    </div><!-- padding_class -->
			</header><!-- inner_top_bar -->
		</div><!-- warpper_top_bar -->
	
	<!-- page -->
	<div class="page">
		<!-- layout -->
		<section class="layout session">
			<div class="popout"></div>
			<!-- padding_class -->
		    <div class="padding_class sessionClass">
		    	<div class="formSearchResp">
						   <form action="search/" class="formResponsive" method="get" id="search_engine" accept-charset="UTF-8">
							  <input id="btnItems" name="q" class="mention" type="text" placeholder="Search..." maxlength="100">	
						      </form>
					</div>
		    <!-- wrapper_grid -->
		     <div class="wrapper_grid floatLeft">
				   
				<?php 
				   //<---- * advertising * --->
				   include 'views/inc/advertising.php';
				   if( Session::get( 'authenticated' ) ) :
					   //<---- * who_follow * --->
				      include 'views/inc/who_to_follow.php';
					   endif;
				   
				   //<---- * trending * --->
				   include 'views/inc/trending.php'; 
				    ?>
				   
				    <!-- Grid 1 -->
				   <div class="grid_1">
				   		<!-- container_grid -->
				   		<div class="container_grid about_pages">
				   			<?php include 'views/inc/footer_session.php'; ?>
				   		</div><!-- container_grid -->
				   </div><!-- Grid 1 -->
				   
			   </div><!-- wrapper_grid -->
			   
			   
			   <!-- Grid 2 -->
			   <div class="grid_2 floatRight">
			   	
			   	<!-- nav_profile -->
		    	<div class="grid_profile">
		    		<!-- container_profile -->
				   		<div class="container_profile">
				   			<a href="<?php echo URL_BASE.$this->info->username; ?>">
				   				<img src="<?php echo URL_BASE.'public/avatar/'.$this->info->avatar; ?>"  class="avatar_large" />
				   				</a>
				   			<!-- profile detail -->
					   			<div class="profile_detail">
					   				<span class="detail_top" >
					   					<a href="<?php echo URL_BASE.$this->info->username; ?>">
					   						<h1><?php echo stripslashes( $this->info->name ); ?></h1> 
					   					</a>
					   					
					   					
					   					<?php if( $this->info->type_account == '1' ): ?>
					   					<img title="Verified" class="verified_img" src="<?php echo URL_BASE; ?>public/img/verified.png"> 
					   					<?php endif; ?>
					   					<?php if( $this->followActive->status == 1 ): ?>
					   					<span class="isFollow">FOLLOWS YOU</span>
					   					<?php endif;?>
					   				</span><!-- detail_top -->
					   			<ul class="user_data">
					   				<strong style="color: #999; font-weight: normal; font-size: 14px;">@<?php echo $this->info->username; ?></strong>
					   			</ul>
					   				
					   			</div><!-- profile_detail -->
					   				
				   			</div><!-- container_profile -->
		    	</div><!-- nav_profile -->
		    	
		    	<h4 class="titleBar">Media</h4>
				<div style="overflow: hidden; padding: 15px;">
				<ul class="media_profile_media">
						
					</ul>
					</div><!-- DIV -->
		</div><!-- Grid 2 -->
			   		
			 </div><!-- padding_class -->
		</section><!-- layout -->
	</div><!-- page -->

   
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery-1.7.1.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.easing.1.3.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.placeholder.1.1.1.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery-ui-1.8.17.custom.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>functions.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>count.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>add.post.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.form.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jqueryTimeago.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.colorbox.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.scroll.user.js"></script>
   
   <?php if( !Session::get( 'authenticated' ) ) : ?>
   <script src="<?php echo $_layoutParams['root_js']; ?>login.sign.up.js"></script>
   <?php endif; ?>
 	
 <script type="text/javascript">
 
 $(".media_galery").colorbox({
   	rel:'galery'
   	});
   	
   	<?php if( $countMedia != 0 ): ?> 
   $('.media_profile_media').scrollPagination({
		nop     : 25, 
		offset  : 0, 
		error   : '',
		delay   : 250,
		               
		scroll  : true, 
		query   : 0,
		file    :'get_all_media.php',
		_userId : <?php echo $this->info->id; ?>,
		totalGlobal :  <?php echo $countMedia; ?>
	});
	  <?php endif; ?> 
	  
	  
   jQuery(document).ready(function($) {
   //=== PLACEHOLDER	
  $(function(){
      $(':input[placeholder]').placeholder();
    });
	
   //====== TIME AGO
     
});//<-------- * DOM * ------>

  </script>

	</body>
</html>
  <?php
else:
	
	header ('HTTP/1.0 404 Not Found');
	include 'public/error/404.php'; // SHOW ERROR 404
	exit;
      
	endif;//<-- COUNT - 0 Result ?>
